services:
  - type: static_site
    name: flutter_web_demo
    env: static
    buildCommand: |
      # Install Flutter SDK
      curl -o flutter.zip https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.13.6-stable.tar.xz
      tar xf flutter.zip
      export PATH="$PATH:`pwd`/flutter/bin"

      # Enable web support in Flutter
      flutter config --enable-web
      flutter doctor

      # Build the Flutter web app
      flutter build web
    staticPublishPath: build/web